### ISSUE TITLE
Build crash when both output destination and splits are specified

### ISSUE THREAD

**Issue by mRcfps** [tuture-dev/tuture#167]
**Describe the bug**
When running `tuture build -o foobar` with multiple parts (i.e. `splits` is given), it crashes.

**To Reproduce**
1. Specifiy `splits` in tuture.yml as usual
2. Run `tuture build -o foobar`
3. See error

**Expected behavior**
Two choices (I don't know which one is better):
- Create a directory with the named specified in `-o` or `--output`, and put all targets into it
- Raise an error and tell the user

**Screenshots**
```
$ tuture build -o build
Error: Source and destination must not be the same.
    at checkPaths (~/OpenSource/tutureproject/tuture/node_modules/fs-extra/lib/copy-sync/copy-sync.js:185:11)
    at Object.copySync (~/OpenSource/tutureproject/tuture/node_modules/fs-extra/lib/copy-sync/copy-sync.js:25:20)
    at ~/OpenSource/tutureproject/tuture/build/commands/build.js:206:36
    at Array.forEach (<anonymous>)
    at Build.saveTutorials (~/OpenSource/tutureproject/tuture/build/commands/build.js:197:19)
    at Build.run (~/OpenSource/tutureproject/tuture/build/commands/build.js:231:14)
    at Build._run (~/OpenSource/tutureproject/tuture/node_modules/@oclif/command/lib/command.js:44:31)
```

**Comment by mRcfps** [comment]
This issue was resolved in commit [0073ebb](https://github.com/tuture-dev/tuture/commit/0073ebbdcaea873038a54fe320396017bc7d90be).
