### ISSUE TITLE
在界面中对our-tuture范例稍作编辑导致异常，且再无法启动

### ISSUE THREAD

**Issue by tiancheng2000** [tuture-dev/tuture#302]
**简要描述 Bug**
原本能正常打开our-tuture范例，说明**一般来说并非环境版本的原因**；但在界面中对our-tuture范例稍作编辑后、却导致异常，且再无法启动编辑界面。希望能改善体验。

**Tuture 版本信息**
@tuture/cli/0.0.6 win32-x64 node-v12.16.2

**详细的报错调用栈信息**
```
TypeError: Cannot set property 'children' of undefined
    at Object.loadCollection (C:/Users/Timothy/AppData/Roaming/npm/node_modules/@tuture/cli/node_modules/@tuture/local-server/dist/index.js:90:36)
    at Object.<anonymous> (C:/Users/Timothy/AppData/Roaming/npm/node_modules/@tuture/cli/lib/utils/git.js:95:42)
    at Generator.next (<anonymous>)
    at fulfilled (C:/Users/Timothy/AppData/Roaming/npm/node_modules/@tuture/cli/node_modules/tslib/tslib.js:112:62)
```

**复现步骤**
复现 Bug 的完整步骤：

1. 按新手教程：复刻`our-tuture`后`tuture up`打开编辑界面
2. 在编辑界面做了一些编辑（具体记不得，可参照添付的`collection.json`）
  [collection.json](https://github.com/tuture-dev/tuture/files/4701494/collection.json.txt)
3. 突然CLI就抛异常中止了
4. 再执行`tuture up` 也无法打开编辑界面

**期望的行为逻辑**
描述一下你本来期望发生的事情。

**屏幕截图**
出错时的屏幕截图（有 GIF 的话就更棒啦！）

**Comment by pftom** [comment]
@tiancheng2000 应该是目前对中文编辑器支持不太友好，可以重新复刻一下，然后继续学习和使用。

原因是这段代码编辑时丢失，后续考虑对内容做校验：

![image](https://user-images.githubusercontent.com/26423749/83257578-4081ff00-a1e7-11ea-89b7-5be5bf1306df.png)

**Comment by tiancheng2000** [comment]
@pftom  了解了，非常感谢！~
